### Pandas 

In [2]:
import pandas as pd
import numpy as np

In [4]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### Create Pandas Dataframe 

In [8]:
df = pd.DataFrame(data=np.arange(0,20).reshape(5,4), index=["Row1", "Row2", "Row3", "Row4", "Row5"],
                                                columns=["Column1", "Column2", "Column3", "Column4"])

In [9]:
# head()
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [10]:
df.tail()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes


In [13]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

## Indexing
### Column name, rowindex[loc], row index and column index number[iloc]

In [16]:
# by Column name
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int64

In [17]:
type(df['Column1'])

pandas.core.series.Series

In [14]:
df[['Column1', 'Column2', 'Column3']]

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [18]:
type(df[['Column1', 'Column2', 'Column3']])

pandas.core.frame.DataFrame

In [ ]:
# by row name loc
df.loc['Row3']

Column1     8
Column2     9
Column3    10
Column4    11
Name: Row3, dtype: int64

In [21]:
type(df.loc['Row3'])

pandas.core.series.Series

In [23]:
df.loc[['Row3', 'Row4']]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15

In [24]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [25]:
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [26]:
df.iloc[2:,1:]

Column2  Column3  Column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [27]:
df.iloc[:,1:]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

### Convert Dataframe into array

In [28]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

### Basic operations

In [30]:
df = pd.DataFrame(data=[[1, np.nan, 2], [1, 3, 4]], index=["Row1", "Row2"],
                                                columns=["Column1", "Column2", "Column3"])

In [31]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [32]:
#checking null value
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [33]:
df['Column3'].value_counts()

Column3
2    1
4    1
Name: count, dtype: int64

In [34]:
df['Column3'].unique()

array([2, 4])