### Numpy Array operations

In [2]:
import numpy as np

### Slicing 

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing : ", arr[2:7])
print("With Step : ", arr[1:8:2])
print("Negative Indexing : ", arr[-3])

# 2D Array Slicing
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print("\n Specific element : ", arr2d[1,2])
print("Row Slicing : ", arr2d[1])
print("Column Slicing : ", arr2d[:,1])

Basic Slicing :  [3 4 5 6 7]
With Step :  [2 4 6 8]
Negative Indexing :  8

 Specific element :  6
Row Slicing :  [4 5 6]
Column Slicing :  [2 5 8]


### Sorting

In [16]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted array : ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("\n Sorted 2d_array by column : ", np.sort(arr_2d_unsorted, axis=0))

Sorted array :  [1 1 2 3 4 5 6 9]

 Sorted 2d_array by column :  [[1 1]
 [2 2]
 [3 3]]


### Filter

In [17]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers : ", even_number)

Even numbers :  [ 2  4  6  8 10]


### Filter with mask

In [18]:
mask = numbers > 5
print("Numbers grater than 5 : ", numbers[mask])

Numbers grater than 5 :  [ 6  7  8  9 10]


### fancy indexing vs np.where()

In [21]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where : ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where :  [ 6  7  8  9 10]


In [22]:
condition_array = np.where(numbers > 5, numbers*4, numbers)
print("Condition array: ", condition_array)

Condition array:  [ 1  2  3  4  5 24 28 32 36 40]


### Adding and removing data

In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print("Concatenate array : ", combined)


Concatenate array :  [1 2 3 4 5 6]


### array compatibilty 

In [24]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

print("Compatibility shapes : ", arr1.shape == arr2.shape == arr3.shape)


Compatibility shapes :  True


In [26]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print("Original array: \n", original)
print("With new row: \n", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column : ", with_new_col)

Original array: 
 [[1 2]
 [3 4]]
With new row: 
 [[1 2]
 [3 4]
 [5 6]]
With new column :  [[1 2 7]
 [3 4 8]]


In [27]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion : ",deleted)  # Output: [1 2 4 5]

Array after deletion :  [1 2 4 5]
